Install injection libraries with agent install script
DataDog/agent-linux-install-script pull request #36
Opened 2023-05-01 20:06 UTC by randomanderson

This PR adds the ability to install autoinstrumentation libraries after setting environment variables.

| Variable name | Description |
| ---------------|------------|
| DD_APM_INSTRUMENTATION_ENABLED | Install host and docker injection unless overridden with a more specific env variable |
| DD_APM_HOST_INJECTION_ENABLED |  Installs or prevents installation of host injection (via `LD_PRELOAD`) |
| DD_APM_DOCKER_INJECTION_ENABLED | Installs or prevents installation of docker injection ( via `daemon.json` ) |
| DD_APM_LIBRARIES | Space separated list of which languages to install support for. Valid values are `js`, `java`, `python`, `dotnet`, `all`.  Defaults to `all` if host or docker injection is enabled | 
| DD_NO_AGENT_INSTALL | If set, don't install the datadog agent. This is useful for the container injection only case. The check is for the existence of the variable, not any particular value. This mirrors DD_INSTALL_ONLY |

* The script does not verify that all combinations of new and existing variables make sense together (for instance `DD_NO_AGENT_INSTALL` and `DD_AGENT_MINOR_VERSION`)
* I removed the `Installing the $nice_flavor package` log statement because it is redundant with `Installing package(s) ...` line that follows and is misleading in some cases.

### Testing
I added few basic checks to the test suite. Only host injection could be tested because of the docker-in-docker issue.

### Additional Info:
* this PR depends on some fixes to the auto inject packages (https://github.com/DataDog/auto_inject/pull/57, https://github.com/DataDog/auto_inject/pull/55, https://github.com/DataDog/auto_inject/pull/54) being released

2023-05-05 13:23 UTC, bkabrda requested changes
Hi :wave: thanks a lot for sending the PR. It looks really good, I just left couple minor comments inline to get addressed and then I can approve. Thanks!

2023-05-05 15:33 UTC, randomanderson commented on install_script.sh.template
> +  read -r -a lib_array <<< "$DD_APM_LIBRARIES"
For the datadog agent, we specifically use space separated lists: https://docs.datadoghq.com/agent/guide/environment-variables/#general-use

2023-05-05 15:36 UTC, randomanderson commented on install_script.sh.template
> +        ERROR_MESSAGE="Unknown apm library: $lib. Must be one of: all, java, js, python, dotnet"
At most there is 1 more language to add: `ruby`. Go and native won't support runtime autoinstrumentation. The alternative is appending the given value to `datadog-apm-library-` and not giving an error until the package is not found. That's a worse user experience

2023-05-09 08:31 UTC, bkabrda commented on install_script.sh.template
> +  read -r -a lib_array <<< "$DD_APM_LIBRARIES"
I didn't even know that. Thanks for the link, let's keep using spaces then.

2023-05-10 00:24 UTC, randomanderson commented on .gitlab-ci.yml
> +test-apm-injection:
added

2023-05-10 00:24 UTC, randomanderson commented on install_script.sh.template
> +host_injection_enabled=
added a check

2023-05-10 00:24 UTC, randomanderson commented on install_script.sh.template
> +host_injection_enabled=
done

2023-05-12 13:49 UTC, randomanderson commented
closing in favor of a new PR that's not from a fork

2023-05-12 13:49 UTC, closed without merging